In [2]:
import numpy as np
import pandas as pd # pandas 패키지의 전체 라이브러리를 로딩
from matplotlib import pyplot as plt
# matplotlib 패키지 덩어리가 커서 그 중에 pyplot만 import하고 pyplot으로 부르겠다

In [6]:
# Creating a Numpy Array
lst = [1, 2, 3, 4]
arr = np.array(lst)
# arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [7]:
# .dtype attribute
print(arr.dtype)
# int32: 32비트로 정수를 표현

# 여러 데이터타입이 모여있을 경우 '<u32' (u=여러 데이터 타입의 혼합)

int32


In [10]:
"""
Size Comparison of ndrray and lis objects
"""

from sys import getsizeof

lst=[1]
print(getsizeof(lst)) # 56->64
#int+object meta info까지 포함

arr = np.array(lst)
print(getsizeof(arr)) # 104 -> 108 
#더 많은 메모리 차지?
#값 자체만 저장하기 때문에 int(4bytes만큼만)
#리스트 내 요소들이 많아질수록 np가 효율적

64
108


In [13]:
"""
Operations with Numpy Arrays
"""
prices = [30, 25, 40, 20, 20, 35, 50, 35]

# With a list
new_prices = [price-5 for price in prices]
print(new_prices)

# With a ndarray
prices_arr = np.array(prices)
prices_arr = prices_arr - 5
print(prices_arr)

# ** operation and np.sqrt

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [23]:
"""
Exercise: Operation with Test Scores
"""

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 +2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2)
manual_adwoa_test_1 = np.array([test_1[1], test_1[2]])
print(manual_adwoa_test_1)

student_scores = np.array([test_1, test_2, test_3])
print(student_scores)

print(student_scores[2,0])

print(student_scores[:,4]) # 4 대신 -1

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [5]:
"""
Logical Operations with Arrays
"""

a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a > 5
print(mask)


# select using logical operations
selected = a[a > 5] # 배열 a의 원소들 중 5보다 큰 것만 selected에 할당
print(selected)

# combined logical operations 논리합: | 논리곱: &
selected = a[(a > 6) | (a < 4)]  # 우선순위가 존재하기 때문에 괄호로 묶어줘야
print(selected)

selected = a[(a > 4) & (a < 8)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
[5 7]


In [10]:
"""
Exercise: Goldilocks Porridge Festival
"""

porridge = np.array([70, 65, 50, 56, 90, 85, 98, 79, 51])

cold = porridge[porridge < 60]
hot = porridge[porridge > 80]
just_right = porridge[(60 < porridge) & (porridge < 80)]

print(cold, "은/는 너무 차가워요")
print(hot, "은/는 너무 뜨거워요")
print(just_right, "은/는 딱 좋아요!")

[50 56 51] 은/는 너무 차가워요
[90 85 98] 은/는 너무 뜨거워요
[70 65 79] 은/는 딱 좋아요!
