In [1]:
import numpy as np

In [11]:
"""
Numpy Array Attributes
"""

# Createing an array

print(np.arange(3))
print(np.arange(3,9))
print(np.arange(3,9,2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [4]:
# Random number generator

np.random.seed(0)
arr1 = np.random.randint(10, size=6)
print(arr1)
arr2 = np.random.randint(10, size=(3,4))
print(arr2)
arr3 = np.random.randint(10, size=(3,4,5))
print(arr3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [6]:
# Attributes
print(arr2)

print("arr2.ndim = ", arr2.ndim)
print("arr2.shape = ", arr2.shape)
print("arr2.size = ", arr2.size)
print("arr2.dtype = ", arr2.dtype)
print("arr2.itemsize = ", arr2.itemsize)
print("arr2.nbytes = ", arr2.nbytes)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
arr2.ndim =  2
arr2.shape =  (3, 4)
arr2.size =  12
arr2.dtype =  int32
arr2.itemsize =  4
arr2.nbytes =  48


In [12]:
"""
Slicing
"""
arr = np.arange(10)
print(arr)

print(arr[3:7])
print(arr[:5])
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [8]:
# Multi-dimensional subarrays

np.random.seed(0)
arr = np.random.randint(10, size=(6,8))
print(arr)

arr_sub = arr[3:5, 4:7]
print(arr_sub)

[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]]
[[5 0 2]
 [3 7 0]]


In [13]:
"""
Subarrays as no-copy views
"""

np.random.seed(1)
arr = np.random.randint(10,size=(3,4))
print(arr,'\n')

arr_sub = arr[:2,:2]
print(arr_sub,'\n')

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]] 



In [17]:
# .copy()
arr = np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])
print(arr)

arr_sub = arr[:2,:2].copy()
print(arr_sub, '\n')

arr_sub[0,0] = 99
print(arr) # 원본은 변하지 않음
print(arr_sub) # 복사본만 값이 변해있음

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[12  5]
 [ 7  6]] 

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[99  5]
 [ 7  6]]


In [19]:
"""
Reshaping of Arrays
"""
arr = np.arange(1,10)
print(arr,'\n')

# reshape()
grid = arr.reshape(3,3)
print(grid, '\n')

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [23]:
# np.newaxis

arr = np.array([1,2,3])
print(arr)
print("arr.ndim = ", arr.ndim) # 차원 갯수
print("arr.shape = ", arr.shape) # 배열 차원 크기

arr_new = arr[np.newaxis, :]
# arr_new = arr[:, np.newaxis] => shape가 (3,1)로 나옴
print(arr_new) # [[]] => 2차원 행렬
print(arr)
print("arr_new.ndim = ", arr_new.ndim) 
print("arr_new.shape = ", arr_new.shape)

[1 2 3]
arr.ndim =  1
arr.shape =  (3,)
[[1 2 3]]
[1 2 3]
arr_new.ndim =  2
arr_new.shape =  (1, 3)


In [31]:
"""
Array Concatenation
"""

# np.concatenate(), np.vstack(), np.hstack()

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr_3 = np.array([7,8,9])

arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total,'\n')

arr_total = np.vstack([arr_1,arr_2,arr_3])
print(arr_total,'\n')

arr_total = np.hstack([arr_1,arr_2,arr_3])
print(arr_total,'\n')

# 2차원일 때
arr_1 = np.array([[1,2,3],[10,20,30]])
arr_2 = np.array([[4,5,6],[40,50,60]])
arr_3 = np.array([[7,8,9],[70,80,90]])

arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total,'\n')
# axis=0: row방향 / axis=1: coloumn방향

arr_total = np.vstack([arr_1,arr_2,arr_3])
print(arr_total,'\n')

arr_total = np.hstack([arr_1,arr_2,arr_3])
print(arr_total,'\n')

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9] 

[[ 1  2  3]
 [10 20 30]
 [ 4  5  6]
 [40 50 60]
 [ 7  8  9]
 [70 80 90]] 

[[ 1  2  3]
 [10 20 30]
 [ 4  5  6]
 [40 50 60]
 [ 7  8  9]
 [70 80 90]] 

[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]] 



In [32]:
"""
Array Splitting
"""

arr = [1,2,3,99,99,3,2,1]
print(arr,'\n')

arr_1, arr_2, arr_3 = np.split(arr,[3,5])
print(arr_1, arr_2, arr_3)

[1, 2, 3, 99, 99, 3, 2, 1] 

[1 2 3] [99 99] [3 2 1]
