In [1]:
import pandas as pd
import numpy as np

In [4]:
"""
numpy.comcatenate()
"""
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]

np.concatenate([x, y, z])


# vstack(): concatenate vertically
# hstack(): concatenate horizontally
print(np.vstack([x,y,z]))
print(np.hstack([x,y,z]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [6]:
"""
pnadas.comcat()
"""

ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
print(pd.concat([ser1, ser2])) # 작성해주는 순서대로 나옴 / 명시적 인덱스라 순서는 상관없음
# Simply comcatenate the two Series objects


1    A
2    B
3    C
4    D
5    E
6    F
dtype: object


In [7]:
# make_df(): create a DataFrame object
def make_df(cols,ind):
    data = {c: [str(c) + str(i) for i in ind]
           for c in cols}
    return pd.DataFrame(data, ind)

print(make_df('ABC', [1,2]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2


In [9]:
# Concatenate the two DataFrame objects

df1 = make_df('AB', [1,2])
df2 = make_df('CD', [3,4])

print(df1, '\n')
print(df2, '\n')
# 둘의 차이는 인덱스 값이 다름 (세로로 붙이기)

print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2 

    C   D
3  C3  D3
4  C4  D4 

     A    B    C    D
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   C3   D3
4  NaN  NaN   C4   D4


In [11]:
df3 = make_df('AB', [0,1])
df4 = make_df('CD', [0,1])

print(df3, '\n')
print(df4, '\n')
# 둘의 차이는 인덱스 값은 같은데 column이 다름 (가로로 붙이기)

print(pd.concat([df3, df4], axis=1))

# print(pd.concat([df3, df4], axis=0))
# 인덱스가 같은데 수직으로 붙일 수 있나? -> 중복된 인덱스값을 가지도록
# df3의 경우 C,D 그리고 df4의 경우 A,B가 없으므로 NaN(=null) 값이 들어감

    A   B
0  A0  B0
1  A1  B1 

    C   D
0  C0  D0
1  C1  D1 

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


In [14]:
"""
concate() Features
"""

# Case 1: Duplicate indices
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])

y.index = x.index # x의 인덱스인 0, 1을 y의 인덱스로 설정해버림

print(x, '\n')
print(y, '\n')

print(pd.concat([x,y]))

    A   B
0  A0  B0
1  A1  B1 

    A   B
0  A2  B2
1  A3  B3 

    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


In [15]:
# Case 2: Catching duplications as errors

try:
    pd.concat([x,y], verify_integrity=True) # 중복 방지했는데 중복돼서 에러
except ValueError as e:
    print("ValueError: ", e) # 에러 나도 종료되지 않게 try, except문 사용

ValueError:  Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


In [16]:
# Case 3: Ignore the index:
print(pd.concat([x,y], ignore_index=True))

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3


In [ ]:
# Case 4: Adding multiindex keys (hierarchical indexing)


In [20]:
"""
concat(): join options
"""

# default: outer join -> union

x = make_df('ABC', [1, 2])
y = make_df('BCD', [3, 4])

print(x, '\n')
print(y, '\n')

print(pd.concat([x,y], join='outer'))


    A   B   C
1  A1  B1  C1
2  A2  B2  C2 

    B   C   D
3  B3  C3  D3
4  B4  C4  D4 

     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


In [21]:
# inner join -> intersection
print(pd.concat([x,y], join='inner'))

    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


In [ ]:
# append()

In [22]:
"""
Join operations
"""

# Prepare the two  DataFrame objects
df1 = pd.DataFrame({'employee': ['Bob','Jake','Lisa','Sue'],
                   'group':['Accounting', 'Engineering', 'Engineering', 'HR']})

df2 = pd.DataFrame({'employee': ['Lisa','Bob','Jake','Sue'],
                   'hire_date':[2014, 2008, 2012, 2014]})

print(df1, '\n')
print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR 

  employee  hire_date
0     Lisa       2014
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [23]:
# One-to-one join
df3 = pd.merge(df1, df2)
print(df3)
# employee를 중심으로

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2014
3      Sue           HR       2014


In [27]:
# Many-to-one join
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                   'supervisor': ['Clary', 'Guido', 'Steve']})

print(df3, '\n')
print(df4, '\n')
# Enginnering이 중복
pd.merge(df3, df4) # 리스트형태 아니고 각각의 매개변수 / df3 = left, df4 = ringt
# concate같이 단순 연결하는 메소드는 두개 이상의 객체들을 한번에 연결할 수 있다 / [a,b,c,d] -> 리스트 인자로 넣어줌
# join과 병합 연산은 반드시 두개의 데이터셋만 합칠 수 있다 / 왼쪽이 첫번째 DF 오른쪽이 두 번째 DF


  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2014
3      Sue           HR       2014 

         group supervisor
0   Accounting      Clary
1  Engineering      Guido
2           HR      Steve 



employee        group  hire_date supervisor
0      Bob   Accounting       2008      Clary
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2014      Guido
3      Sue           HR       2014      Steve

In [28]:
# Many-to-Many join
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                             'Engineering', 'Engineering',
                             'HR','HR'],
                   'sklls': ['math', 'spreadsheets', 'coding',
                            'linux','spreadsheets', 'organization']})

print(df1, '\n')
print(df5, '\n')

print(pd.merge(df1, df5))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR 

         group         sklls
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization 

  employee        group         sklls
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization


In [30]:
"""
Specifying the merge Key
"""

# 'on' argument: use a common column as merge key

print(df1,'\n')
print(df2,'\n')

df1['age'] = pd.Series([20, 42, 37, 25])
df2['age'] = pd.Series([37, 20, 42, 25])

print(df1,'\n')
print(df2,'\n')

# 공통되는 열은 employee와 age
print(pd.merge(df1, df2, on='employee'))
# employee를 기준으로 병합했기 때문에 df1의 age와 df2의 age를 다른 것으로 인식해 _x, _y로 구분해버림

  employee        group  age
0      Bob   Accounting   20
1     Jake  Engineering   42
2     Lisa  Engineering   37
3      Sue           HR   25 

  employee  hire_date  age
0     Lisa       2014   37
1      Bob       2008   20
2     Jake       2012   42
3      Sue       2014   25 

  employee        group  age
0      Bob   Accounting   20
1     Jake  Engineering   42
2     Lisa  Engineering   37
3      Sue           HR   25 

  employee  hire_date  age
0     Lisa       2014   37
1      Bob       2008   20
2     Jake       2012   42
3      Sue       2014   25 

  employee        group  age_x  hire_date  age_y
0      Bob   Accounting     20       2008     20
1     Jake  Engineering     42       2012     42
2     Lisa  Engineering     37       2014     37
3      Sue           HR     25       2014     25


In [33]:
# 'left_on' and 'right_on' arguments:
df3 = pd.DataFrame({'name': ['Bob', 'Jake','Lisa', 'Sue'],
                   'salary': [70000, 80000, 120000, 90000]})

print(df1,'\n')
print(df3,'\n')
# employee와 name이 같은 정보를 담고 있음
print(pd.merge(df1, df3, left_on='employee', right_on='name'))

  employee        group  age
0      Bob   Accounting   20
1     Jake  Engineering   42
2     Lisa  Engineering   37
3      Sue           HR   25 

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000 

  employee        group  age  name  salary
0      Bob   Accounting   20   Bob   70000
1     Jake  Engineering   42  Jake   80000
2     Lisa  Engineering   37  Lisa  120000
3      Sue           HR   25   Sue   90000


In [37]:
# 'left_index' and 'right_index' arguments
print(df1, '\n')
print(df2, '\n')
# column 중 하나를 인덱스로 사용할 수 있음
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
print(df1a, '\n')
print(df2a, '\n')

# 이렇게 될 경우 employee를 기준으로 나머지 두개의 DataSet을 병합하는 것이 가능하다
print(pd.merge(df1a, df2a))
# column기준으로 병합했기 때문에 employee의 내용은 사라진다

print(pd.merge(df1a, df2a, left_index=True, right_index=True))
# 이렇게 되면 age는 _x, _y로 나눠짐

  employee        group  age
0      Bob   Accounting   20
1     Jake  Engineering   42
2     Lisa  Engineering   37
3      Sue           HR   25 

  employee  hire_date  age
0     Lisa       2014   37
1      Bob       2008   20
2     Jake       2012   42
3      Sue       2014   25 

                group  age
employee                  
Bob        Accounting   20
Jake      Engineering   42
Lisa      Engineering   37
Sue                HR   25 

          hire_date  age
employee                
Lisa           2014   37
Bob            2008   20
Jake           2012   42
Sue            2014   25 

         group  age  hire_date
0   Accounting   20       2008
1  Engineering   42       2012
2  Engineering   37       2014
3           HR   25       2014
                group  age_x  hire_date  age_y
employee                                      
Bob        Accounting     20       2008     20
Jake      Engineering     42       2012     42
Lisa      Engineering     37       2014     37
Sue       